# Usa una imagen base oficial de Python
FROM python:3.10.11

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el contenido actual en /app
COPY . /app

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto 8000
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
